{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute html_class='form-control'}
{let datetime=cond( is_set( $#collection_attributes[$attribute.id] ), $#collection_attributes[$attribute.id].content, $attribute.content )}
    <div class="row">

        <div class="col">
            <label class="sr-only" for="{$attribute_base}_datetime_year_{$attribute.id}">{'Year'|i18n( 'design/standard/content/datatype' )}:</label>
            <input class="{$html_class}" id="{$attribute_base}_datetime_year_{$attribute.id}" type="number" name="{$attribute_base}_datetime_year_{$attribute.id}" size="5"
                   placeholder="{'Year'|i18n( 'design/standard/content/datatype' )}"
                   value="{if $datetime.is_valid}{$datetime.year}{/if}"/>
        </div>

        <div class="col">
            <label class="sr-only" for="{$attribute_base}_datetime_month_{$attribute.id}">{'Month'|i18n( 'design/standard/content/datatype' )}:</label>
            <input class="{$html_class}" id="{$attribute_base}_datetime_month_{$attribute.id}" type="number" name="{$attribute_base}_datetime_month_{$attribute.id}" size="3"
                   placeholder="{'Month'|i18n( 'design/standard/content/datatype' )}"
                   value="{if $datetime.is_valid}{$datetime.month}{/if}"/>
        </div>

        <div class="col">
            <label class="sr-only" for="{$attribute_base}_datetime_day_{$attribute.id}">{'Day'|i18n( 'design/standard/content/datatype' )}:</label>
            <input class="{$html_class}" id="{$attribute_base}_datetime_day_{$attribute.id}" type="number" name="{$attribute_base}_datetime_day_{$attribute.id}" size="3"
                   placeholder="{'Day'|i18n( 'design/standard/content/datatype' )}"
                   value="{if $datetime.is_valid}{$datetime.day}{/if}"/>

        </div>

        <div class="col">
            <label class="sr-only" for="{$attribute_base}_datetime_hour_{$attribute.id}"<label class="sr-only" for="{$attribute_base}_datetime_year_{$attribute.id}">{'Hour'|i18n( 'design/standard/content/datatype' )}:</label>
            <input class="{$html_class}" id="{$attribute_base}_datetime_hour_{$attribute.id}" type="number" name="{$attribute_base}_datetime_hour_{$attribute.id}" size="3"
                   placeholder="{'Hour'|i18n( 'design/standard/content/datatype' )}"
                   value="{if $datetime.is_valid}{$datetime.hour}{/if}"/>
        </div>

        <div class="col">
            <label class="sr-only" for="{$attribute_base}_datetime_minute_{$attribute.id}">{'Minute'|i18n( 'design/standard/content/datatype' )}:</label>
            <input class="{$html_class}" id="{$attribute_base}_datetime_minute_{$attribute.id}" type="number" name="{$attribute_base}_datetime_minute_{$attribute.id}" size="3"
                   placeholder="{'Minute'|i18n( 'design/standard/content/datatype' )}"
                   value="{if $datetime.is_valid}{$datetime.minute}{/if}"/>
        </div>

        {if $attribute.contentclass_attribute.data_int2|eq(1)}
            <div class="col">
                <label class="sr-only" for="{$attribute_base}_datetime_second_{$attribute.id}">{'Second'|i18n( 'design/standard/content/datatype' )}:</label>
                <input class="{$html_class}" id="{$attribute_base}_datetime_second_{$attribute.id}" type="number" name="{$attribute_base}_datetime_second_{$attribute.id}" size="3"
                       placeholder="{'Second'|i18n( 'design/standard/content/datatype' )}"
                       value="{if $datetime.is_valid}{$datetime.second}{/if}"/>
            </div>
        {/if}

    </div>
{/let}
{/default}
