{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute html_class='form-control'}
{let date=cond( is_set( $#collection_attributes[$attribute.id] ), $#collection_attributes[$attribute.id].content, $attribute.content )}
    <div class="row">
        <div class="col">
            <label class="sr-only" for="{$attribute_base}_date_year_{$attribute.id}">{'Year'|i18n( 'design/standard/content/datatype' )}:</label>
            <input class="{$html_class}" type="number" name="{$attribute_base}_date_year_{$attribute.id}" id="{$attribute_base}_date_year_{$attribute.id}" size="5"
                   placeholder="{'Year'|i18n( 'design/standard/content/datatype' )}"
                   value="{if $date.is_valid}{$date.year}{/if}"/>
        </div>

        <div class="col">
            <label class="sr-only" for="{$attribute_base}_date_month_{$attribute.id}">{'Month'|i18n( 'design/standard/content/datatype' )}:</label>
            <input class="{$html_class}" type="number" name="{$attribute_base}_date_month_{$attribute.id}" id="{$attribute_base}_date_month_{$attribute.id}" size="3"
                   placeholder="{'Month'|i18n( 'design/standard/content/datatype' )}"
                   value="{if $date.is_valid}{$date.month}{/if}"/>
        </div>

        <div class="col">
            <label class="sr-only" for="{$attribute_base}_date_day_{$attribute.id}">{'Day'|i18n( 'design/standard/content/datatype' )}:</label>
            <input class="{$html_class}" type="number" name="{$attribute_base}_date_day_{$attribute.id}" id="{$attribute_base}_date_day_{$attribute.id}" size="3"
                   placeholder="{'Day'|i18n( 'design/standard/content/datatype' )}"
                   value="{if $date.is_valid}{$date.day}{/if}"/>
        </div>

    </div>
{/let}
{/default}
