{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute html_class='form-control'}
{let time=cond( is_set( $#collection_attributes[$attribute.id] ), $#collection_attributes[$attribute.id].content, $attribute.content )}
<div class="row">

    <div class="col">
        <label class="sr-only" for="{$attribute_base}_time_hour_{$attribute.id}">{'Hour'|i18n( 'design/standard/content/datatype' )}:</label>
        <input class="{$html_class}"
               placeholder="{'Hour'|i18n( 'design/standard/content/datatype' )}"
               type="number" id="{$attribute_base}_time_hour_{$attribute.id}"
               name="{$attribute_base}_time_hour_{$attribute.id}"
               size="3" value="{if $time.is_valid}{$time.hour}{/if}" />
    </div>

    <div class="col">
        <label class="sr-only" for="{$attribute_base}_time_minute_{$attribute.id}">{'Minute'|i18n( 'design/standard/content/datatype' )}:</label>
        <input class="{$html_class}"
               placeholder="{'Minute'|i18n( 'design/standard/content/datatype' )}"
               type="number" id="{$attribute_base}_time_minute_{$attribute.id}"
               name="{$attribute_base}_time_minute_{$attribute.id}"
               size="3" value="{if $time.is_valid}{$time.minute}{/if}" />
    </div>

    {if $attribute.contentclass_attribute.data_int2|eq(1)}
    <div class="col">
        <label class="sr-only" for="{$attribute_base}_time_second_{$attribute.id}">{'Second'|i18n( 'design/standard/content/datatype' )}:</label>
        <input class="{$html_class}"
               placeholder="{'Second'|i18n( 'design/standard/content/datatype' )}"
               type="number" id="{$attribute_base}_time_second_{$attribute.id}"
               name="{$attribute_base}_time_second_{$attribute.id}"
               size="3" value="{if $time.is_valid}{$time.second}{/if}" />
    </div>
    {/if}

</div>
{/let}
{/default}
