{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $all_list = fetch( 'bootstrapitalia', 'comuni_italiani', hash('grouped', true()) )}
    <div class="block">
        <input type="checkbox" name="ContentClass_opcom_ismultiple_{$class_attribute.id}" {if $class_attribute.content.multiple_choice}checked="checked"{/if}/>
        <b>{'Multiple choice'|i18n( 'design/standard/class/datatype' )}</b>
        <input type="hidden" name="ContentClass_opcom_multiple_choice_{$class_attribute.id}_exists" value="1" />
    </div>

    <div class="block">
        <label for="default_selection_{$class_attribute.id}">{'Default selection'|i18n( 'design/standard/class/datatype' )}:</label>
        <select id="default_selection_{$class_attribute.id}" name="ContentClass_opcom_default_list_{$class_attribute.id}[]" multiple="multiple">
            {foreach $all_list as $group1 => $items}
                <optgroup label="{$group1|wash()}"></optgroup>
                {foreach $items as $group2 => $objects}
                    <optgroup label="{$group2|wash()}"></optgroup>
                    {foreach $objects as $object}
                        <option value="{$object.pro_com_t|wash}" {if $class_attribute.content.default_list|contains($object.pro_com_t)}selected="selected"{/if}>{$object.comune}</option>
                    {/foreach}
                {/foreach}
            {/foreach}
        </select>
        <input type="hidden" name="ContentClass_opcom_default_selection_{$class_attribute.id}_exists" value="1" />
    </div>
{undef $all_list}
