{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let matrix=$attribute.content}    
<div class="my-3 font-sans-serif">
    {foreach $matrix.rows.sequential as $index => $row}
        <div class="font-sans-serif card card-teaser card-teaser-info rounded shadow-sm p-3 card-teaser-info-width mt-0 mb-3">
            <div class="card-body">
                {if or($row.columns[0]|ne(''), $row.columns[1]|ne(''))}
                <h5>
                    <span class="category-top">
                      {if $row.columns[0]|ne('')}{$row.columns[0]|wash()}{/if}
                    </span>
                    <p class="card-title big-heading">{if or($row.columns[2]|eq(''), $row.columns[2]|eq('0'))}{'FREE'|i18n('bootstrapitalia')}{else}{$row.columns[2]|wash()} {$row.columns[3]|wash()}{/if}</p>
                </h5>
                <p class="mt-4">{if $row.columns[1]|ne('')}{$row.columns[1]|wash()}{/if}</p>
                {else}
                    <h5>
                        <p class="card-title big-heading">{if or($row.columns[2]|eq(''), $row.columns[2]|eq('0'))}{'FREE'|i18n('bootstrapitalia')}{else}{$row.columns[2]|wash()} {$row.columns[3]|wash()}{/if}</p>
                    </h5>
                {/if}
            </div>
        </div>
    {/foreach}
</div>
{/let}
