<?php

$eZTemplateOperatorArray = [
    [
        'class' => 'OpenPABootstrapItaliaOperators',
        'operator_names' => [
            'display_icon',
            'parse_search_get_params',
            'filtered_search_params_query_string',
            'openpa_roles_parent_node_id',
            'clean_filename',
            'class_identifier_by_id',
            'page_block',
            'current_theme',
            'current_theme_has_variation',
            'primary_color',
            'header_color',
            'footer_color',
            'is_bookmark',
            'privacy_states',
            'menu_item_tree_contains',
            'lang_selector_url',
            'valuation_translation',
            'max_upload_size',
            'explode_contact',
            'is_empty_matrix',
            'cookie_consent_config_translations',
            'parse_layout_blocks',
            'parse_attribute_groups',
            'tag_tree_has_contents',
            'edit_attribute_groups',
            'get_default_integer_value',
            'satisfy_main_entrypoint',
            'user_token_url',
            'user_profile_url',
            'user_api_base_url',
        ],
    ],
];
