{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{set $classification = cond( and(is_set( $align ), $align ), concat( $classification, ' object-', $align ), $classification )}
{def $show_default_table = true()}
{if $classification|eq('accordion')}
    {def $data = $rows|parse_table()}
    {if count($data.rows)}
        {set $show_default_table = false()}
        {include uri='design:content/datatype/view/ezxmltags/table_accordion.tpl'}
    {/if}
{elseif $classification|eq('procedure')}
    {def $data = $rows|parse_table()}
    {if count($data.rows)}
        {set $show_default_table = false()}
        {include uri='design:content/datatype/view/ezxmltags/table_procedure.tpl'}
    {/if}
{elseif $classification|eq('timeline')}
    {def $data = $rows|parse_table()}
    {if count($data.rows)}
        {set $show_default_table = false()}
        {include uri='design:content/datatype/view/ezxmltags/table_timeline.tpl'}
    {/if}
{/if}
{if $show_default_table}
    <div class="table-responsive">
        <table class="table {if $classification}{$classification|wash}{else}table-striped{/if}"{*if ne($border|trim,'')} border="{$border}"{/if} cellpadding="{first_set($cellpadding, '2')}" cellspacing="0"{if ne($width|trim,'')} width="{$width}"{/if*}{if and(is_set( $summary ), $summary)} summary="{$summary|wash}"{/if}{if and(is_set( $title ), $title)} title="{$title|wash}"{/if}>
            {if and(is_set( $caption ), $caption)}<caption>{$caption|wash}</caption>{/if}
            {$rows}
        </table>
    </div>
{/if}
{undef $show_default_table}