<?php /*

[AvailableHandlers]
Handlers[bootstrapitalia_icon]=OpenPABootstrapItaliaIconExtraParameter
Handlers[attribute_group]=OpenPABootstrapItaliaAttributeGroupExtraParameter
Handlers[table_view]=OpenPABootstrapItaliaTableViewClassExtraParameters
Handlers[line_view]=OpenPABootstrapItaliaLineViewClassExtraParameters
Handlers[card_small_view]=OpenPABootstrapItaliaCardSmallViewClassExtraParameters
 
*/ ?>
