<?php /* #?ini charset="utf-8"?

[EnvironmentSettingsPresets]
AvailablePresets[]=calendar
AvailablePresets[]=data
AvailablePresets[]=extrageo

[EnvironmentSettingsPresets_calendar]
CheckAccess=false
Debug=enabled
PHPClass=OpenPABootstrapItaliaCalendarEnvironmentSettings

[EnvironmentSettingsPresets_data]
CheckAccess=false
Debug=disabled
PHPClass=OpenPABootstrapItaliaDataEnvironmentSettings

[EnvironmentSettingsPresets_extrageo]
CheckAccess=false
Debug=disabled
PHPClass=OpenPABootstrapItaliaExtrageoEnvironmentSettings

[EnvironmentSettingsPresets_content]
PHPClass=OpenPABootstrapItaliaContentEnvironmentSettings

[EnvironmentSettingsPresets_useraware]
PHPClass=OpenPABootstrapItaliaUserAwareEnvironmentSettings

[EnvironmentSettingsPresets_datatable]
PHPClass=OpenPABootstrapItaliaDatatableEnvironmentSettings

[AttributeConverters]
Converters[has_temporal_coverage]=FullRelationsAttributeConverter
Converters[opening_hours_specification]=FullRelationsAttributeConverter

[ExtraDataProviders]
Class[event]=ezfIndexSubAttributeGeo
Class[private_organization]=ezfIndexSubAttributeGeo
Class[office]=ezfIndexSubAttributeGeo
Class[public_organization]=ezfIndexSubAttributeGeo
Class[public_service]=ezfIndexSubAttributeGeo
Class[administrative_area]=ezfIndexSubAttributeGeo

[GeneralSettings]
DatasetClassIdentifier=dataset

[DatiTrentinoItTest]
OrganizationBuilder=OpenPABootstrapItaliaCkanOrganizationBuilder
Client=OpenPABootstrapItaliaCkanClient
Converter=OpenPABootstrapItaliaCkanConverter
DatasetGenerator=OpenPABootstrapItaliaCkanDatasetGenerator

[DatiTrentinoIt]
OrganizationBuilder=OpenPABootstrapItaliaCkanOrganizationBuilder
Client=OpenPABootstrapItaliaCkanClient
Converter=OpenPABootstrapItaliaCkanConverter
DatasetGenerator=OpenPABootstrapItaliaCkanDatasetGenerator

*/ ?>