{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute html_class='full'}
{let selected_id_array=$attribute.content}

{def $defs = decode_banner_color()}

{* Always set the .._selected_array_.. variable, this circumvents the problem when nothing is selected. *} 
<input type="hidden" name="{$attribute_base}_ezselect_selected_array_{$attribute.id}" value="" />
{foreach $attribute.class_content.options as $item}
<div class="row">
    <div class="col-4">
        <div class="form-check">
            <input type="radio"
                   name="{$attribute_base}_ezselect_selected_array_{$attribute.id}[]"
                   value="{$item.id}"
                   id="color-{$attribute.id}-{$item.id}"
                   class="form-check-input"
                   {if $selected_id_array|contains( $item.id )}checked="checked"{/if} />
            <label class="form-check-label w-100" for="color-{$attribute.id}-{$item.id}">
                <div class="card card-teaser p-1 {if is_set($defs[$item.name])}{$defs[$item.name].background_color_class}{/if}">
                    <small class="d-block text-truncate m-0 {if is_set($defs[$item.name])}{$defs[$item.name].text_color_class}{/if}">
                        {$item.name|wash( xhtml )}
                    </small>
                </div>
            </label>
        </div>
    </div>
</div>
{/foreach}

{/let}
{/default}
