{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base='ContentObjectAttribute' html_class='full' placeholder=false()}
{if $attribute.object.state_identifier_array|contains('opencity_lock/locked')}
    <input type="hidden" name="{$attribute_base}_data_text_{$attribute.id}" value="{$attribute.content|wash( xhtml )}" />
    <textarea class="{$html_class}" disabled>{$attribute.content|wash}</textarea>
{else}
    <textarea {if $placeholder}placeholder="{$placeholder}"{/if} id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}"
              class="{$html_class} ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
              name="{$attribute_base}_data_text_{$attribute.id}" cols="70" rows="{$attribute.contentclass_attribute.data_int1}">{$attribute.content|wash}</textarea>
{/if}
{/default}
