{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute html_class='full' placeholder=false()}
{def $anac_import_enabled = ezini('BandoCigSettings', 'AnacImportEnabled', 'openpa.ini')|eq('enabled')}
{if $anac_import_enabled}
<p class="text-muted small mt-1 mb-1"><em>{'Questo campo viene aggiornato automaticamente tramite l\'integrazione con ANAC e non può essere modificato manualmente.'|i18n('bootstrapitalia')}</em></p>
{/if}
{include uri=concat('design:content/datatype/edit/', $attribute.data_type_string, '.tpl')}
{undef $anac_import_enabled}
{/default}
