{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute  html_class='full' placeholder=false()}
{def $allow_api_sequential_id = ezini('AlboPretorioSettings', 'AllowApiSequentialId', 'openpa.ini')|eq('enabled')}
  <div class="form-group form-check mb-0">
      {if $attribute.content|eq('')}
        {if $allow_api_sequential_id}
          <p class="text-muted"><em>{'Non è possibile assegnare un numero progressivo manualmente perché è attiva la funzionalità di importazione automatica atti'|i18n('bootstrapitalia')}</em></p>
        {else}
          <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}"
                 class="form-check-input ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
                 type="checkbox"
                 name="{$attribute_base}_data_openpaalbo_{$attribute.id}" {$attribute.data_int|choose( '', 'checked="checked"' )}
                 value=""/>
          <label class="form-check-label"
                 for="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}">
              {if $placeholder}{$placeholder}{else}{$attribute.contentclass_attribute.name}{/if}
          </label>
        {/if}
      {else}
        <p>
          <b>Numero progressivo albo pretorio:</b>
            {if $attribute.content|eq('pending')}
              <em>{'Il numero progressivo sarà assegnato alla pubblicazione'|i18n('bootstrapitalia/albo_pretorio')}</em>
              <input type="hidden"
                     name="{$attribute_base}_data_openpaalbo_{$attribute.id}"
                     value="1"/>
            {else}
              <code>{$attribute.content|wash()}</code>
            {/if}
        </p>
      {/if}
  </div>
{undef $allow_api_sequential_id}
{/default}