{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute  html_class='full' placeholder=false()}
  <div class="form-group form-check mb-0">
      {if $attribute.content|eq('')}
        <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}"
               class="form-check-input ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
               type="checkbox"
               name="{$attribute_base}_data_openpaalbo_{$attribute.id}" {$attribute.data_int|choose( '', 'checked="checked"' )}
               value=""/>
        <label class="form-check-label"
               for="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}">
            {if $placeholder}{$placeholder}{else}{$attribute.contentclass_attribute.name}{/if}
        </label>
      {else}
        <p>
          <b>Numero progressivo albo pretorio:</b>
            {if $attribute.content|eq('pending')}
              <em>{'Il numero progressivo sarà assegnato alla pubblicazione'|i18n('bootstrapitalia/albo_pretorio')}</em>
              <input type="hidden"
                     name="{$attribute_base}_data_openpaalbo_{$attribute.id}"
                     value="1"/>
            {else}
              <code>{$attribute.content|wash()}</code>
            {/if}
        </p>
      {/if}
  </div>
{/default}