{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}

{if $attribute.content}
    <button class="btn btn-sm btn-danger" type="submit" name="CustomActionButton[{$attribute.id}_delete_binary]"  title="{'Remove the file from this draft.'|i18n( 'design/standard/content/datatype' )}">
        <span class="fa fa-trash"></span>
    </button>
    <a href="{concat( 'content/download/', $attribute.contentobject_id, '/', $attribute.id,'/version/', $attribute.version , '/file/', $attribute.content.original_filename|urlencode )|ezurl(no)}">
        {$attribute.content.original_filename|wash( xhtml )} {$attribute.content.mime_type|wash( xhtml )} {$attribute.content.filesize|si( byte )}
    </a>
{else}
    <div class="position-relative">
        <input type="hidden" name="MAX_FILE_SIZE" value="{$attribute.contentclass_attribute.data_int1}000000"/>
        <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}"
               class="inputfile"
               name="{$attribute_base}_data_binaryfilename_{$attribute.id}"
               type="file" />
        <label class="btn btn-sm btn-info"
               for="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg>
            <span>{'Upload file'|i18n('bootstrapitalia')}</span>
        </label>
    </div>
{/if}
{/default}
{run-once}
{ezscript_require(array('jquery.custom-file-input.js'))}
{ezcss_require(array('custom-file-input.css'))}
{/run-once}