{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}
{let matrix=$attribute.content}
    <table class="table table-sm">
        <tr>
            <th class="tight" width="1">&nbsp;</th>
            {section var=ColumnNames loop=$matrix.columns.sequential}
                <th class="size-sm">{$ColumnNames.item.name}</th>
            {/section}
        </tr>
        {section show=$matrix.rows.sequential}
            {section var=Rows loop=$matrix.rows.sequential sequence=array( bglight, bgdark )}
                <tr class="{$Rows.sequence}">
                    {* Remove. *}
                    <td style="padding:0" width="1">
                        <label style="margin: 0;padding: 10px;" for="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_remove_{$Rows.index}">
                            <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_remove_{$Rows.index}"
                                   class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
                                   type="checkbox" name="{$attribute_base}_data_matrix_remove_{$attribute.id}[]"
                                   value="{$Rows.index}"
                                   data-select
                                   title="{'Select row for removal.'|i18n( 'design/standard/content/datatype' )}"/>
                        </label>
                    </td>

                    {* Custom columns. *}
                    {section var=Columns loop=$Rows.item.columns}
                        <td>
                            <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_matrix_cell_{$Rows.index}_{$Columns.index}"
                                   class="form-control ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
                                   type="text" name="{$attribute_base}_ezmatrix_cell_{$attribute.id}[]"
                                   data-cell
                                   value="{$Columns.item|wash( xhtml )}"/></td>
                    {/section}

                </tr>
            {/section}
        {/section}
    </table>
{/let}
{/default}