{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let matrix=$attribute.content}
    <div class="link-list-wrapper">
        <ul class="link-list">
            {foreach $matrix.rows.sequential as $row}
                <li>
                    <span>{$row.columns[1]|wash()} {if $row.columns[0]|ne('')}({$row.columns[0]|wash()}){/if}</span>
                </li>
            {/foreach}
        </ul>
    </div>
{/let}
