{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let matrix=$attribute.content}    
<div class="my-3">
    {foreach $matrix.rows.sequential as $index => $row}    
    <dl class="row {if $index|gt(0)} border-top pt-3{/if}">
        {if or($row.columns[0]|ne(''), $row.columns[1]|ne(''))}
        <dt class="col-8 col-sm-9 font-weight-normal">
            {if $row.columns[0]|ne('')}{$row.columns[0]|wash()}{/if} {if $row.columns[1]|ne('')}{if $row.columns[0]|ne('')}({/if}{$row.columns[1]|wash()}{if $row.columns[0]|ne('')}){/if}{/if}
        </dt>
        <dd class="col-4 col-sm-3 text-center">
            <span style="font-size: 1em" class="badge badge-light bg-light font-weight-normal ml-2 ms-2">{if or($row.columns[2]|eq(''), $row.columns[2]|eq('0'))}{'FREE'|i18n('bootstrapitalia')}{else}{$row.columns[2]|wash()} {$row.columns[3]|wash()}{/if}</span>
        </dd>
        {else}
        <dd class="col">
            <span style="font-size: 1em" class="badge badge-light bg-light font-weight-normal mt-1">{if or($row.columns[2]|eq(''), $row.columns[2]|eq('0'))}{'FREE'|i18n('bootstrapitalia')}{else}{$row.columns[2]|wash()} {$row.columns[3]|wash()}{/if}</span>
        </dd>
        {/if}
    </dl>
    {/foreach}   
</div>
{/let}
