{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let matrix=$attribute.content}
<p>{foreach $matrix.rows.sequential as $row}{$row.columns[0]|wash()}{delimiter}, {/delimiter}{/foreach}</p>
{/let}
