{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let matrix=$attribute.content}
<table class="table table-sm">
<thead class="thead-dark">
<tr>
{section var=ColumnNames loop=$matrix.columns.sequential}
    <th class="size-sm"><small class="text-nowrap">{$ColumnNames.item.name|wash( xhtml )}</small></th>
{/section}
</tr>
</thead>
{section var=Rows loop=$matrix.rows.sequential sequence=array( bglight, bgdark )}
<tr class="{$Rows.sequence}">
    {section var=Columns loop=$Rows.item.columns}
        <td>
            {if $Columns.index|eq(4)}
                {if $Columns.item|eq(1)} Mandante
                {elseif $Columns.item|eq(2)} Mandataria
                {elseif $Columns.item|eq(3)} Associata
                {elseif $Columns.item|eq(4)} Capogruppo
                {elseif $Columns.item|eq(5)} Consorziata
                {/if}
            {else}
            {$Columns.item|wash( xhtml )}
            {/if}
        </td>
    {/section}
</tr>
{/section}
</table>
{/let}
