{* DO NOT EDIT THIS FILE! Use an override template instead. *}

{def $types = array('Telefono', 'E-mail', 'Fax', 'Cellulare', 'Sito web', 'PEC')}
{def $contacts = array('segreteria', 'supporto tecnico/specialistico', 'amministrazione')}
{default attribute_base=ContentObjectAttribute}
{let matrix=$attribute.content}

    {* Matrix. *}
{section show=$matrix.rows.sequential}
    <table class="table" cellspacing="0">

        <tr>
            <th class="tight">&nbsp;</th>
            {section var=ColumnNames loop=$matrix.columns.sequential}
                <th>{$ColumnNames.item.name}</th>
            {/section}
        </tr>

        {section var=Rows loop=$matrix.rows.sequential sequence=array( bglight, bgdark )}
            <tr class="{$Rows.sequence}">

                {* Remove. *}
                <td>
                    <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_remove_{$Rows.index}"
                           class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
                           type="checkbox" name="{$attribute_base}_data_matrix_remove_{$attribute.id}[]"
                           value="{$Rows.index}"
                           title="{'Select row for removal.'|i18n( 'design/standard/content/datatype' )}"/></td>

                {* Custom columns. *}
                {section var=Columns loop=$Rows.item.columns}
                    <td>
                        {if $matrix.columns.sequential[$Columns.index].identifier|eq('type')}
                            {def $selected = $Columns.item}
                            <select name="{$attribute_base}_ezmatrix_cell_{$attribute.id}[]"
                                    id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_matrix_cell_{$Rows.index}_{$Columns.index}"
                                    class="form-control ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}">                                
                                {foreach $types as $type}
                                    <option value="{$type|wash}" {if $selected|eq($type)}selected="selected"{/if}>{$type|wash}</option>
                                {/foreach}
                            </select>
                            {undef $selected}
                        {elseif $matrix.columns.sequential[$Columns.index].identifier|eq('contact')}
                            {def $selected = $Columns.item}
                            <select name="{$attribute_base}_ezmatrix_cell_{$attribute.id}[]"
                                    id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_matrix_cell_{$Rows.index}_{$Columns.index}"
                                    class="form-control ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}">                                
                                <option></option>
                                {foreach $contacts as $contact}
                                    <option value="{$contact|wash}" {if $selected|eq($contact)}selected="selected"{/if}>{$contact|wash}</option>
                                {/foreach}
                            </select>
                            {undef $selected}
                        {else}
                        <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_matrix_cell_{$Rows.index}_{$Columns.index}"
                               class="form-control ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
                               type="text"
                               name="{$attribute_base}_ezmatrix_cell_{$attribute.id}[]"
                               value="{$Columns.item|wash( xhtml )}"/>
                        {/if}
                    </td>

                {/section}

            </tr>
        {/section}
    </table>
{/section}


<div class="clearfix">
{* Buttons. *}
{if $matrix.rows.sequential}
    <div class="float-left">
    <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_remove_selected"
           class="btn btn-sm btn-danger ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
           type="submit" name="CustomActionButton[{$attribute.id}_remove_selected]"
           value="{'Remove selected'|i18n( 'design/standard/content/datatype' )}"
           title="{'Remove selected rows from the matrix.'|i18n( 'design/standard/content/datatype' )}"/>
    </div>
{/if}
    &nbsp;&nbsp;
{let row_count=sub( 40, count( $matrix.rows.sequential ) ) index_var=0}
{if $row_count|lt( 1 )}
    {set row_count=0}
{/if}
<div class="{if $matrix.rows.sequential}float-right{else}float-left{/if}">
    <div class="input-group">
        <select id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_add_count"
                class="custom-select form-control-sm matrix_cell ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
                name="{$attribute_base}_data_matrix_add_count_{$attribute.id}"
                title="{'Number of rows to add.'|i18n( 'design/standard/content/datatype' )}">
            <option value="1">1</option>
            {section loop=$row_count}
                {set index_var=$index_var|inc}
                {delimiter modulo=5}
                    <option value="{$index_var}">{$index_var}</option>
                {/delimiter}
            {/section}
        </select>
        <div class="input-group-append">
        <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_new_row"
               class="btn btn-sm btn-success ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
               type="submit" name="CustomActionButton[{$attribute.id}_new_row]"
               value="{'Add rows'|i18n('design/standard/content/datatype')}"
               title="{'Add new rows to the matrix.'|i18n( 'design/standard/content/datatype' )}"/>
        </div>
    </div>
</div>
{/let}
</div>

{/let}
{/default}