{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute html_class='full'}
{let selected_id_array=$attribute.content}

{* Always set the .._selected_array_.. variable, this circumvents the problem when nothing is selected. *} 
<input type="hidden" name="{$attribute_base}_ezselect_selected_array_{$attribute.id}" value="" />
<div class="row row-cols-1 row-cols-md-4">
{foreach $attribute.class_content.options as $item}
    <div class="col mb-4">
        <div class="form-check">
            <input type="radio"
                   name="{$attribute_base}_ezselect_selected_array_{$attribute.id}[]"
                   value="{$item.id}"
                   id="color-{$attribute.id}-{$item.id}"
                   class="form-check-input"
                   {if $selected_id_array|contains( $item.id )}checked="checked"{/if} />
            <label class="form-check-label w-100" for="color-{$attribute.id}-{$item.id}">
                <div class="card card-teaser p-1 {$item.name|wash( xhtml )}">
                    <small class="d-block text-truncate m-0 text-{$item.name|wash( xhtml )}">
                        {$item.name|wash( xhtml )}
                    </small>
                </div>
            </label>
        </div>
    </div>
{/foreach}

{/let}
{/default}
